# Generated by Django 6.0.3 on 2026-04-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('overlay_color', models.CharField(default='rgba(0,0,0,0.4)', help_text='Overlay color for text readability', max_length=20)),
                ('cta_text', models.CharField(default='Shop Now', max_length=50)),
                ('cta_link', models.CharField(blank=True, help_text='URL or product category link', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('wants_fashion_updates', models.BooleanField(default=True)),
                ('wants_exclusive_offers', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
            },
        ),
        migrations.CreateModel(
            name='FeaturedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='collections/')),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(limit_choices_to={'is_featured': True}, related_name='collections', to='products.product')),
            ],
            options={
                'verbose_name': 'Featured Collection',
                'verbose_name_plural': 'Featured Collections',
                'ordering': ['display_order'],
            },
        ),
    ]
