# Generated by Django 6.0.3 on 2026-03-30 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gossip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The headline of your gossip - make it fetch!', max_length=200)),
                ('content', models.TextField(help_text="Spill ALL the tea! Don't leave out any details.")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this spicy tea was served')),
                ('posted_by', models.ForeignKey(help_text='The person who spilled the tea ☕', on_delete=django.db.models.deletion.CASCADE, related_name='gossips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gossip Post',
                'verbose_name_plural': 'All Gossip Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
