"""
Django settings for gossip_project_core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2e697^(_@=dfks2qa9n346uyi&gwf%)%eb13ixe)m2thqlo7%='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 🎭 REST Framework & JWT Authentication - our VIP bouncers!
    'rest_framework',
    'rest_framework_simplejwt',
    # 👥 Users App - for custom user authentication
    'users',
    # 🌐 CORS headers - allow frontend to connect
    'corsheaders',
    # 💼 E-commerce Apps - Vogue-style luxury fashion
    'products',
    'cart',
    'orders',
    'payments',
    'reviews',
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 🌐 CORS middleware - must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gossip_project_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gossip_project_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

# Use custom user model
AUTH_USER_MODEL = 'users.User'

# 🌐 CORS Configuration - Allow frontend to connect
# In development, we allow localhost:3000 (React default)
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

# For development, you can also allow credentials
CORS_ALLOW_CREDENTIALS = True

# 💳 Stripe Configuration (for production, use environment variables)
STRIPE_SECRET_KEY = 'sk_test_YOUR_STRIPE_SECRET_KEY'  # Replace with actual key
STRIPE_PUBLISHABLE_KEY = 'pk_test_YOUR_STRIPE_PUBLISHABLE_KEY'  # Replace with actual key

# 📸 Media Files Configuration (for product images)
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 🎭 Django REST Framework Configuration
# Where we configure how our API behaves - like setting the dress code for the Plastics!
REST_FRAMEWORK = {
    # Use JWT tokens for authentication - like a VIP club bouncer!
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Only authenticated users can access the API - no gatecrashers allowed!
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# 🔐 JWT (JSON Web Token) Settings
# Configure how long your VIP pass lasts
from datetime import timedelta

SIMPLE_JWT = {
    # Access token expires after 5 minutes - short and secure like a trendy outfit!
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    # Refresh token lasts 1 day - come back anytime queen!
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # Rotate refresh tokens when used - extra security, very fetch!
    'ROTATE_REFRESH_TOKENS': True,
    # Don't blacklist old refresh tokens (for development)
    'BLACKLIST_AFTER_ROTATION': False,
    # Use Django's default authentication to verify username/password
    'AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
